### ISSUE TITLE
Incomplete Documentations

### ISSUE THREAD

**Issue by John-Almardeny** [sailab-code/gnn#1]

**Comment by John-Almardeny** [comment]
Thanks for this work. Highly appreciated and it is useful.

On your website, the GNN work is perfectly explained in theory. However, looking through your implementation code, methods are not completely documented. For example, it is not enough to mentione that the `Evaluate` function does *evaluates*, rather it is more convenient to detail its work and what metrics it is based on...etc. Likewise all other methods.
 
Also, it would be nice if you can leave some comments between the lines of codes for better understanding of the workflow.

**Comment by mtiezzi** [comment]
Thank you very much for your feedback.
It is the first release, so the comments are still incomplete and under development.
I will update the code. 
Briefly speaking, the evaluate method can be used to test the accuracy and performance of the model (it's output its the value of the accuracy reached by the model).
The predict method can be used to obtain only the outputs of the model.

**Comment by mtiezzi** [comment]
I updated the comments for the suggested methods.
