### ISSUE TITLE
Example provided is inconsistent 

### ISSUE THREAD

**Issue by John-Almardeny** [sailab-code/gnn#2]
In Simple usage example, `Net` in import and `set_load()` in implementation are undefined.
Can you provide a complete working simple usage example?

Thanks.

**Comment by mtiezzi** [comment]
You can find some complete examples in the "Example" page in the documentation site
https://sailab.diism.unisi.it/gnn/auto_examples/index.html

The Net.py file and set_load() depend on the specific task you have to attack, for this reason it is not possible to define them in a general way.
