### ISSUE TITLE
Examples Datasets

### ISSUE THREAD

**Issue by John-Almardeny** [sailab-code/gnn#3]
Can you elaborate how did you generate the datasets in the examples that are in format of `.mat` files?
Also, if possible to associate a Graph diagram representing one of the examples.
Thanks.

**Comment by mtiezzi** [comment]
The example dataset have been generated trough  the old MATLAB implementation of the GNN software.
You can find it in the following link http://www.dii.unisi.it/~franco/Research/GNNDownload.php

Moreover, you can find a description of the Subgraph and Clique problem in the original paper:
https://ieeexplore.ieee.org/document/4700287
I will try to enrich our description with a diagram.
Thank you very much for your feedback

**Comment by mtiezzi** [comment]
If you need more info do not esitate to comment. However the original code has also a manual that describes the creation of the datasets.

**Comment by John-Almardeny** [comment]
@mtiezzi  OK thanks. The example not to be complicated. Just for example, it's enough to have 4 to 5 nodes graph and explain the process, starting with nodes in a dictionary for example and how they are being transformed to a proper input ...etc.

**Comment by mtiezzi** [comment]
Perfect. In a couple weeks I will update the code with a toy example.

**Comment by mtiezzi** [comment]
I have update the code with a  novel utility that should simplify the input creation, the `from_EN_to_GNN()` function in the `gnn_utils.py` file. 
Moreover I added other two simple examples ( GNN_simple. and GNN_Karate ) to show how to use this new method. 
Now, simply describing the dataset with two matrices (EN), you can obtain the formatted input.
You can find a description in the site [Formatting example](https://sailab.diism.unisi.it/gnn/tutorial.html#simple-toy-example-for-input-formatting)
