### ISSUE TITLE
Missing Net.py File

### ISSUE THREAD

**Issue by John-Almardeny** [sailab-code/gnn#4]
It is mentioned in the documentation that:

> Net.py contains the implementation of several task oriented structures, 
> such as state and output networks, loss functions and metrics definion.
> Users` may implement their own version of the Net file, for a specific task.

Which implies that there is `Net.py` module. Checking out the repo.  and there is not such a file.

**Comment by mtiezzi** [comment]
In the Example folder of the repo you can find three different versions of the Net file, one for each task 
(Net_Subgraph, Net_Clique, Net_Mutag).
They are simple example, for different task you have to define your own model/performance metrics.

Thanks for the feedback
