### ISSUE TITLE
some questions about arcnode in the code

### ISSUE THREAD

**Issue by lihuiliullh** [sailab-code/gnn#6]
Dear GNN authors:

The way you build arcnode matrix is a little hard for me to understand. Can you give me a little example?

In the code, you build arcnode matrix like this:
#########
mt = adj[["id_1", "id_2"]].values
arcnode = np.zeros((mt.shape[0], max_id + 1))
arcnode = SparseMatrix(indices=np.stack((mt[:, 0], np.arange(len(mt))), axis=1), values=np.ones([len(mt)]), dense_shape=[max_id + 1, len(mt)])
arcnode_batch.append(arcnode)
##########

It is very different from the data structure in your blog. It will be very helpful if you could give a little example.

Thanks.

**Comment by mtiezzi** [comment]
Hi,
It is exactly the same format given in the blog. 

For simplicity and as requested in a previous issue, I added a simple example for input formatting,
which you can see also in [the link](https://sailab.diism.unisi.it/gnn/tutorial.html#simple-toy-example-for-input-formatting).

In the repo, it corresponds to the file [ GNN_simple](https://github.com/mtiezzi/gnn/blob/master/examples/GNN_simple.py) in the example folder.
Moreover, I added an utility to facilitate the input creation, using the EN matrices (**gnn_utils.from_EN_to_GNN(E, N_tot)**).
See the link [https://sailab.diism.unisi.it/gnn/tutorial.html#en-input](https://sailab.diism.unisi.it/gnn/tutorial.html#en-input)

**Comment by lihuiliullh** [comment]
I know what you mean now. The arcnode matrix is transposed! Yeah, it is the same as what you say in the blog.

Thanks.

**Comment by mtiezzi** [comment]
Exactly, it is transposed (and created already transposed for a code optimization reason).
You are welcome
 ;)

**Comment by mtiezzi** [comment]
I updated the link to the blog, now it is hosted on GitHub Pages.
Best
