### ISSUE TITLE
A question about gnn/gnn_utils.py

### ISSUE THREAD

**Issue by JarvisXX** [sailab-code/gnn#8]
Hello! Appreciate your great job! 
However, I have a question in the code of gnn/gnn_utils.py. In line 280, there is `inp = np.concatenate((E[:, 1:2], feat), axis=1)`. The _inp_ should be _[id_p, id_c, label_p, label_c]_ according to the algorithm (and the note). However, `E[:, 1:2]` seems to be _id_c_ only, leaving out _id_p_. Am I misunderstanding this?

**Comment by mtiezzi** [comment]
Hello, 
Thank you very much for your appreciation. 
The _id_c_ index is used to gather the neighboring node state from the previous iteration ([here for a more in depth analysis](https://sailab.diism.unisi.it/gnn/GNN/model.html#equation-equaz)).
Hence, the _id_p_ index is not used. For this reason, I removed it when I introduced the `from_EN_to_GNN` method (in a more recent release than the original one), and the _id_c_ became the first column of the input.

In fact, if you look closely at the `convergence()` method (in the `GNN.py` file), you can see that I gather  the neighboring node state using as index the first column (i.e., neighboring ids, column 0), and that I compose the input taking the node features, starting from the second column. So, it is coherent with the input I defined (I gather the first column, hence the neighbor id _id_c_).

Concluding, the code was fine, but not the note.

However, the old implementation by Scarselli (MATLAB) used the  [id_p, id_c, label_p, label_c] notation, and also it's data (which I import with the subgraph, clique and mutag dataset). 
Hence, with the introduction of the EN_matrix input  I broke the compatibility with the old datasets.

To make all more clear, I made a novel commit where all should be coherent. 
If you previously used the `from_EN_to_GNN` to create the input, it was fine. 
In this new commit I changed the `from_EN_to_GNN` method as you suggested, but also the `convergence()` method (in the `GNN.py` file).

Let me know if it  sounds right.

**Comment by mtiezzi** [comment]
I also added the handling of semisupervised tasks (`mask_flag`)

**Comment by JarvisXX** [comment]
The new version works fine! Thank you for your comments!

**Comment by JarvisXX** [comment]
I think the `Loss` and `Metric` in _Net_*.py_ files should also be updated to be consistent with `mask_flag`.

**Comment by mtiezzi** [comment]
Thanks!
Karate example updated! (Net_Karate.py)
